baseurl = "/"
languageCode = "en-us"
title = "Nuevas Fronteras con r"
theme = "hugo-lithium"
googleAnalytics = "UA-142402614-1"
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Proyecto"
    url = "/proyecto/"
    weight = 1
[[menu.main]]
    name = "Contacto"
    url = "/contacto/"
    weight = 4
[[menu.main]]
    name = "Curso"
    url = "/curso/"
    weight = 2
[[menu.main]]
    name = "Únete"
    url = "/unete/"
    weight = 3

[params]
    description = "Nos dedicamos a formar Analistas de datos con R "

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "10x Faster con R"

